# Generated by Django 5.2.8 on 2025-11-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='bank_account_name',
            field=models.CharField(default='Not Provided', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disaster',
            name='bank_account_number',
            field=models.CharField(default='0000000000', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disaster',
            name='ifsc_code',
            field=models.CharField(default='UNKNOWNIFSC', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disaster',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
