# Generated by Django 5.2.8 on 2025-11-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_disaster_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='donation_proofs/'),
        ),
        migrations.AddField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(default='UNKNOWN_TXN', max_length=100),
            preserve_default=False,
        ),
    ]
